jobs:
  - job: 1
    ami-id: ${PLACE_AMI_ID_HERE}
    platform: ten_x_v2
    user-tags:
      Job: 1
      Project: 10178
      Sample: DEV_IGO_00001
    index: s3://seqc-public/genomes/hg38_long_polya/
    barcode-files: s3://seqc-public/barcodes/ten_x_v2/flat/
    genomic-fastq: s3://seqc-public/test/ten_x_v2/genomic/
    barcode-fastq: s3://seqc-public/test/ten_x_v2/barcode/
    upload-prefix: s3://dp-lab-test/seqc/aws/ten_x_v2/single-cell//seqc-results/
    output-prefix: test1
    no-filter-low-coverage: ""
    min-poly-t: "0"
    email: chunj@mskcc.org
    star-args: "runRNGseed=0"
  - job: 2
    ami-id: ${PLACE_AMI_ID_HERE}
    platform: ten_x_v2
    user-tags:
      Job: 2
      Project: 10178
      Sample: DEV_IGO_00002
    filter-mode: snRNA-seq
    max-insert-size: 2304700
    index: s3://seqc-public/genomes/hg38_long_polya_snRNAseq/
    barcode-files: s3://seqc-public/barcodes/ten_x_v2/flat/
    genomic-fastq: s3://seqc-public/test/ten_x_v2/genomic/
    barcode-fastq: s3://seqc-public/test/ten_x_v2/barcode/
    upload-prefix: s3://dp-lab-test/seqc/aws/ten_x_v2/single-nucleus/seqc-results/
    output-prefix: test2
    email: chunj@mskcc.org
    star-args: "runRNGseed=0"
